Fix failed CI jobs
```
Run shards update --skip-postinstall --skip-executables
I: Resolving dependencies
I: Fetching https://github.com/grottopress/shield.git
I: Fetching https://github.com/crystal-ameba/ameba.git
I: Fetching https://github.com/luckyframework/lucky_cache.git
E: Unable to satisfy the following requirements:

- `lucky_cache (~> 0.2.0)` required by `avram 1.4.2+git.commit.4790149297823545e65fe3187b58036a16eb3693`
- `lucky_cache (~> 0.1.1)` required by `lucky 1.4.0+git.commit.6a8b2a46364887eb6a475a8cf86b394d49c26e74`
E: Failed to resolve dependencies
Error: Process completed with exit code 1.
```

See <https://github.com/GrottoPress/samba/actions/runs/23374825937/job/68005003732>.