Revert "Truncate database once before specs"
Fixes compile error:

```
In spec/setup/database.cr:8:22

 8 | BaseModel.database.truncate(restart_identity: false)
                        ^-------
Error: no parameter named 'restart_identity'
```

This reverts commit 13da73cb23ca916197e252a53c8019a5a8ce5ca7.